version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: smartcv-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartcv
    ports:
      - "3306:3306"

